services:
  api:
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '1'
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8000:8000"

  worker:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3

  database:
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '2'
          memory: 4G

  cache:
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  monitoring:
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    internal: true
    attachable: true
