services:
  api:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8081:8081"

  worker:
    ports:
      - "8082:80"  # Changed worker port from 8081 to 8082 to avoid conflict
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3

  database:
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '2'
          memory: 4G

  cache:
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  monitoring:
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    internal: true
    attachable: true
